
%% graph one
PCD_graph_x = [25, 26, 28.5, 30.9, 33.33, 37.5, 40.6, 43.5, 60, 69, 80, 87.9, 93.9, 100];
PCD_graph_y = [54.7, 46, 48, 47, 50.8, 60.5, 64.1, 65.6, 67.2, 66.4, 63, 59.25, 55.5, 49.2];

EID_x = [20, 50.9, 51, 60, 80, 86, 94, 100];
EID_y = [21, 39.8, 31.5, 42, 64, 69.5, 75.8, 81];

figure()
plot(PCD_graph_x, PCD_graph_y, EID_x, EID_y);
title('Graph One')

PCD_integral_60 = trapz(PCD_graph_x(1:9), PCD_graph_y(1:9));
PCD_integral_80 = trapz(PCD_graph_x(1:11), PCD_graph_y(1:11));
PCD_integral_100 = trapz(PCD_graph_x, PCD_graph_y);


EID_integral_60 = trapz(EID_x(1:4), EID_y(1:4));
EID_integral_80 = trapz(EID_x(1:5), EID_y(1:5));
EID_integral_100 = trapz(EID_x, EID_y);


%% graph two
Energy_60B = [10, 15, 20, 25, 30, 35, 40, 45, 50, 60];
Photon_60B = [0, 0.1, 1.5, 2.3, 3.8, 3.5, 2.5, 2.1, 1.7, 0];
Photon_60B = Photon_60B * 10^10;
Integral_60B_25 = trapz(Energy_60B(4:10), Photon_60B(4:10));
Integral_60B_20 = trapz(Energy_60B(3:10), Photon_60B(3:10));


Energy_80B = [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80];
Photon_80B = [0, 0.1, 1.5, 3.6, 5, 5.4, 5, 4.1, 3.8, 2.2, 1, 0];
Photon_80B = Photon_80B * 10^10;
Integral_80B_25 =  trapz(Energy_80B(4:12), Photon_80B(4:12));
Integral_80B_20 =  trapz(Energy_80B(3:12), Photon_80B(3:12));


Energy_100B = [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100];
Photon_100B = [0, 0.1, 2, 4, 6, 6.5, 6.3, 6.1, 5.7, 4, 2.5, 2, 1, 0];
Photon_100B = Photon_100B * 10^10;
Integral_100B_25 =  trapz(Energy_100B(4:14), Photon_100B(4:14));
Integral_100B_20 =  trapz(Energy_100B(3:14), Photon_100B(3:14));
figure()
plot(Energy_100B, Photon_100B, Energy_80B, Photon_80B, Energy_60B, Photon_60B);
title('Graph 2')


% Signal Strength Output at Various X-Ray Strengths
weights =  0.000001 * 600 * 0.00000625;
PCD_60 = PCD_integral_60 * Integral_60B_25 * weights;
PCD_80 = PCD_integral_80 * Integral_80B_25 * weights;
PCD_100 = PCD_integral_100 * Integral_100B_25 * weights;

EID_60 = EID_integral_60 * Integral_60B_20 * weights;
EID_80 = EID_integral_80 * Integral_80B_20 * weights;
EID_100 = EID_integral_100 * Integral_100B_20 * weights;
 

figure()
names = ["PCD 60 vs EID 60"; "PCD 80 vs EID 80"; "PCD 100 vs EID 100"]; 
integrals = [PCD_60 EID_60; PCD_80 EID_80; PCD_100 EID_100];
bar(names, integrals);
title("Signal Strength Output at Various X-Ray Strengths")


% with body extinction
constant = exp(-50*0.4);
PCD_60 = PCD_60*constant;
EID_60 = EID_60*constant;
PCD_80 = PCD_80*constant;
EID_80 = EID_80*constant;
PCD_100 = PCD_100*constant;
EID_100 = EID_100*constant;
figure()
names = ["PCD 60 vs EID 60"; "PCD 80 vs EID 80"; "PCD 100 vs EID 100"]; 
integrals = [PCD_60 EID_60; PCD_80 EID_80; PCD_100 EID_100];
bar(names, integrals);
title("Signal Strength Considering Body Extinction")


% /home/chuc `r  k/Documents/working/12482/EECE4649/slides/ruth.m
% Wed Jun  5 12:37:53 2024

details=1;

sums=[];sumspc=[];
%testsignals=[0:0.1:3];
%testsignals=[0:0.1:3]/20;
testsignals=[EID_60, EID_80, EID_100];  % Mean number of photons (equals S)

for nbar=testsignals;

mbar=300; % Number of electrons generated by one photon (gain)

qbar=300; % Number of electrons generated by noise.

n=0:10;
m=0:500;q=0:500;

nthreshold=400;

pn=poisspdf(n,nbar);
if(details>1);figure;stem(n,pn);grid on;
xlabel('n, Photons');ylabel('P(n)');end;

pm=poisspdf(m,mbar);
if(details>1);figure;stem(m,pm);grid on;
xlabel('m, Signal Electrons');ylabel('P(m)');end;

pq=poisspdf(q,qbar);
if(details>1);figure;stem(m,pm);grid on;
xlabel('q, Noise Electrons');ylabel('P(q)');end;


nt=0:20000;
pt=zeros(size(nt));
pt(1:length(pq))=pq*poisspdf(0,nbar);
for nn=1:max(n);
    pt(nn*mbar+m)=pt(nn*mbar+m)+poisspdf(nn,nbar)*poisspdf(m,mbar);
end;

if(details>0);figure;plot(nt,pt);grid on;
    moose=axis;axis([0,1000,0,moose(4)]);
xlabel('nt, Total Electrons');ylabel('P(nt)');
title(['Signal = ',num2str(nbar),' Photons']);end;

testsum=(sum((nt-mbar).*pt)+sqrt(mbar))/mbar

overthr=find(nt>nthreshold);    
testsumpc=sum((nt(overthr)-mbar).*pt(overthr))/mbar

sums=[sums,testsum];
sumspc=[sumspc,testsumpc];
end;

figure;plot(testsignals,sums,'b-o',...
            testsignals,sumspc,'g-x',...
            testsignals,testsignals,'k-+');grid on;
                      


    
